env:
  global:
    - CC_TEST_REPORTER_ID=465e77cd56b0d0b3da3708ce8a44e85dd499743e5525b910186e4da227b61bab
language: ruby
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
before_install:
  - gem install bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - RAILS_ENV=test bundle exec rails   db:create db:migrate db:seed
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
