default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: autoforce
  password: autoforce

development:
  <<: *default
  database: used_models_development

test:
  <<: *default
  database: used_models_test

production:
  <<: *default
  database: used_models_production
